### PR TITLE
Fix for GetAbbreviatedEraName on mono with .net version +4.5

### PR DESCRIPTION
**Pull request by andrevdm**
This method was already using reflection. This fix checks if
cultureInfo.DateTimeFormat.GetAbbreviatedEraName(era) exists and
if so uses it rather than cultureInfo.Calendar.AbbreviatedEraNames

This fixes https://github.com/fsharp/FSharp.Data/issues/823

### CODE REVIEW

**Comment by andrevdm** [comment]
The AppVeyor error does not seem related to this change. The error is 
"Could not load file or assembly 'FSharp.Core, Version=4.4.0.0"

**Comment by andrevdm** [comment]
For the record this fix uses reflection as I don't want to make assumptions about what is available on different .net versions across windows and mono (and I can't reliably test that either). Its not as clear as I would have liked but the existing method already used reflection to get around the version differences. So I don't think this is adding much complexity

**Comment by ovatsus** [comment]
It was already using reflection as the alternative way of doing it was not working on Mono before, they had a big somewhere, can't remember exactly now

**Comment by andrevdm** [comment]
@ovatsus Perhaps the off-by-one bug, referenced here? https://github.com/fsharp/FSharp.Data/issues/426

**Comment by ovatsus** [comment]
Yes. That was it. Maybe if that bug was fixed on latest Mono we can just remove the if altogether and not use reflection?

**Comment by andrevdm** [comment]
That would be better, yes. My concern would be for people using older versions of mono. Perhaps there is some way to handle that from the code. I'll take a look ASAP and see if I can think of something

**Comment by andrevdm** [comment]
Ok... I can't see a better way :(. 

I find it strange that there is a call to "cultureInfo.DateTimeFormat.GetAbbreviatedEraName(era)" in the "else" branch of the "if runningOnMono" as GetAbbreviatedEraNames is only available for .net 4.5 and 4.6 [1]. 

The simplest way would be to remove the mono check and use GetAbbreviatedEraNames but then you need +4.5. So I think the reflection approach I used here is the safest as it will work on both old and new versions of mono. 

Lets hear what everyone else says? But I'm happy with this unless there are any objections.

[1] https://msdn.microsoft.com/en-us/library/system.globalization.datetimeformatinfo.getabbreviatederaname%28v=vs.110%29.aspx

**Comment by tpetricek** [comment]
I submitted a fix for this in #840

**Pull request closed without merging**
