### PR TITLE
[WIP] Support for nested types in tables, lists and schema.org

### PR DESCRIPTION
**Pull request by colinbull**
This PR is still very much a WIP but I wanted to give some visibility and get some feedback as to where I'm at. This PR adds support for nested html structures. Specifically Table within Tables and List within Tables and also basic support for any types defined using schema.org attributes `itemscope`, `itemtype` and `itemprop`.

Things still left to do, 
- The HTML Generator, is currently a copy of the XML Generator as I wasn't sure whether any changes would be necessary. However I don't think there are and we could probably just write a transform to take the HTML generated tree and turn it into an XElement and just re-use the XML Generator / inference.
- Schema.org is still a work in progress. 
- UoM support needs to be re-introduced, although I don't think the XML provider currently supports UoM anyway. 
- Nested List's don't have brilliant support at the minute. I'm pretty sure this could be made better.

Things we could add in the future.
- We could add a general DOM type which allowed navigation of the entire HTML document.  
- Img's and anchors could have a type with a download method.

Anyway, Here is an example of what is supported so far: 

```
let [<Literal>] data= 
    """<html>
           <body>
               <table>
                   <tr>
                        <td>Date</td>
                        <td>Distance (m)</td>
                        <td>Time (s)</td>
                        <td>Column 3</td>
                        <td>Column 4</td>
                        <td>Results</td>
                   </tr>
                   <tr>
                       <td>01/01/2013 12:00</td>
                       <td>2</td><td>30.5</td>
                       <td>
                           <div itemscope itemtype ="http://schema.org/Movie">
                             <h1 itemprop="name">Avatar</h1>
                             <div itemprop="director" itemscope itemtype="http://schema.org/Person">
                             Director: <span itemprop="name">James Cameron</span> (born <span itemprop="birthDate">August 16, 1954 </span>)
                             </div>
                             <span itemprop="genre">Science fiction / Blue People</span>
                             <a href="../movies/avatar-theatrical-trailer.html" itemprop="trailer">Trailer</a>
                           </div>
                       </td>
                       <td>
                            <ul>
                                <li>1</li>
                                <li>1</li>
                                <li>1</li>
                                <li>1</li>
                            </ul>
                       </td>
                       <td>
                            <table>
                                <tr>
                                    <th>TimePoint</th><th>Value</th>
                                </tr>
                                <tr>
                                    <td>1</td><td>1.234</td>
                                </tr>
                                <tr>
                                    <td>2</td><td>8.67</td>
                                </tr>
                            </table>
                       </td>
                   </tr>
                   <tr>
                       <td>01/01/2013 12:00</td>
                       <td>1.5</td>
                       <td>30.5</td>
                       <td>
                           <div itemscope itemtype ="http://schema.org/Movie">
                             <h1 itemprop="name">Alien</h1>
                             <div itemprop="director" itemscope itemtype="http://schema.org/Person">
                             Director: <span itemprop="name">James Cameron</span> (born <span itemprop="birthDate">August 17, 1954 </span>)
                             </div>
                             <span itemprop="genre">Science fiction</span>
                             <a href="../movies/avatar-theatrical-trailer.html" itemprop="trailer">Trailer</a>
                           </div>
                           <div itemscope itemtype="http://schema.org/rating">
                              <div  itemprop="val">
                                <meta value="8" />
                             </div>
                           </div>
                       </td>
                       <td>
                            <ul>
                                <li>1</li>
                                <li>1</li>
                                <li>1</li>
                                <li>1</li>
                            </ul>
                       </td>
                       <td>
                            <table>
                                <tr>
                                    <th>TimePoint</th><th>Value</th>
                                </tr>
                                <tr>
                                    <td>1</td><td>1.234</td>
                                </tr>
                                <tr>
                                    <td>2</td><td>8.67</td>
                                </tr>
                            </table>
                       </td>
                   </tr>
               </table>
           </body>
       </html>"""

let table1 = HtmlProvider<data>.GetSample().Tables.Table1
let headers = table1.Headers
let date = table1.Rows |> Seq.map (fun x -> x.Date) |> Seq.toList
let movieName = table1.Rows |> Seq.map (fun x -> x.Column3.Movie.Director.Person.BirthDate) |> Seq.toList
let nestedTables = table1.Rows |> Seq.collect (fun x -> x.Results.Table.Rows |> Seq.map (fun r -> r.Value)) |> Seq.toList     
```

### CODE REVIEW

**Comment by ovatsus** [comment]
I'd like to get this going, I'll try to review this soon

**Comment by ovatsus** [comment]
Yikes, this PR is already an year old, sorry Collin.
I want to get this functionality in, so I'll try to merge this piece by piece

**Comment by colinbull** [comment]
Do you want me to have a go at merging master back into this to make the final merge easier?

**Comment by ovatsus** [comment]
I think I'll try to cherry pick instead, as there are two changes mixed here, and merging will be quite hard

**Comment by dsyme** [comment]
@colinbull Maybe you could bring this up-to-date after all?

**Comment by dsyme** [comment]
Closing very old PR

**Pull request closed without merging**
