### PR TITLE
Improve parsing performance

### PR DESCRIPTION
**Pull request by eulerfx**
...by pre-allocating StringBuilder, and ResizeArray for records and arrays. Also, reduce allocations and ops during numeric parsing by avoiding use of Option and active patterns.

This resulted in about a 20% parsing performance improvement in terms of time, as well as reduced gen 0 and gen 1 collections:

> Real: 00:00:25.131, CPU: 00:00:25.109, GC gen0: 3445, gen1: 4, gen2: 1

vs 

> Real: 00:00:19.631, CPU: 00:00:19.640, GC gen0: 1689, gen1: 3, gen2: 1

The test parsed a 4KB JSON string 500k times.

For comparison, parsing using `Newtonsoft.Json.Linq.JToken.Parse` recorded:

> Real: 00:00:38.252, CPU: 00:00:38.234, GC gen0: 3363, gen1: 305, gen2: 1

### CODE REVIEW

**Comment by eulerfx** [comment]
I also couldn't build the test project as is. I ran Json tests only by excluding provider modules.

**Comment by ovatsus** [comment]
Didn't know we were already faster than JSON.NET :)

**Comment by eulerfx** [comment]
@ovatsus ahh nice catch! Luckily, the array and pairs perf improvement was marginal - more-so the allocation reduction. The StringBuilder was the biggie. The numeric parsing was also marginal, maybe just under a second improvement. I'm assuming due to option. Trying to parse int64 first also showed improvement, but it is obviously dependent on the input. I'll try it again, and update the PR.

Another win will be from having numeric parsers which take string ranges. We can either wait for a BCL update are internalize the substring parsing implementations.

**Comment by eulerfx** [comment]
Fixed invalid use of buffers and reverted numeric parsing. Still very good!

> Real: 00:00:19.727, CPU: 00:00:19.734, GC gen0: 1888, gen1: 4, gen

**Comment by ovatsus** [comment]
Thanks!

**Pull request merged**
