### PR TITLE
Use content type encoding

### LINKED ISSUE #819: PUT and POST request don't respect ContentType charset
```f#
let! res = Http.AsyncRequest (url, 
                              headers=[("Content-Type", "application/json; charset=utf-8")],
                              httpMethod = "POST",
                              body = httpRequestBody)
```

Still uses the default encoding set [here](https://github.com/fsharp/FSharp.Data/blob/master/src/Net/Http.fs#L306). 

It should use the charset shouldn't it?

### PR DESCRIPTION
**Pull request by albertjan**
Fixes #819

### CODE REVIEW

**Comment by albertjan** [comment]
I don't think the appveyor build fails because of anything I did. :smile:

**Comment by ovatsus** [comment]
Thanks, sorry for the delay, had forgot about this :(

**Comment by albertjan** [comment]
No worries, the work around was easy enough :smile:. Happy this landed though. And in one go :smile:.

**Comment by ovatsus** [comment]
Reverted 2nd commit as it was causing merge issues with other PR's

**Comment by albertjan** [comment]
Ah ok sure an overzealous editors did that :smile: there is an open statement in there that you'll need. 

Sorry this causes issues.

**Pull request merged**
