### PR TITLE
Xsd Support (via @giacomociti)

### PR DESCRIPTION
**Pull request by baronfel**
This is just #1004 rebased on top of latest master.

### CODE REVIEW

**Comment by baronfel** [comment]
test failures on mono will be fixed once the encodings branch is merged and this is rebased off of that.

**Comment by baronfel** [comment]
rebased on top of latest master

**Comment by baronfel** [comment]
The travis failures here are in setup, is there a way for you to rerun just those jobs?

**Comment by giacomociti** [comment]
@baronfel  I fetched your rebased branch and submitted a new TravisCI build. Got http timeout issues [this time](https://travis-ci.org/giacomociti/FSharp.Data/builds/345922074) but maybe I missed something

**Comment by baronfel** [comment]
Let me rebase once more onto master, there have been some test fixes since the last time I did.

**Comment by ovatsus** [comment]
Closes #57

**Comment by ovatsus** [comment]
Can you add a couple of signature tests and add a little bit of documentation about this in XmlProvider.fsx?

**Comment by ovatsus** [comment]
Replacesd by #1149

**Pull request closed without merging**
