### PR TITLE
So Long, and Thanks for All the Fish, Freebase

### PR DESCRIPTION
**Pull request by ovatsus**
Freebase will be gone by 31 March

### CODE REVIEW

**Comment by ovatsus** [comment]
Closes #764

**Comment by dsyme** [comment]
Shedding a tear for this one :( Lets try to resurrect it against wikidata or the google knowledge graph (when api is available) or Microsoft satori (when api is available) or the like...But in a separate package of course...

**Comment by tpetricek** [comment]
Guess I have a couple of samples to fix now... Thanks to @colinbull for the HTML provider!

[And yes, nothing wrong with the PR, as far as I can see.]

**Comment by ovatsus** [comment]
I'd stay away from anything Google for now, they're closing too much stuff, and haven't heard nothing about Satori going open.
Is DbPedia a good replacement?

**Pull request merged**
