### PR TITLE
Remove pin on old FsCheck version and update all dependencies

### PR DESCRIPTION
**Pull request by ovatsus**

### CODE REVIEW

**Comment by ovatsus** [comment]
@forki, I had to upgrade the test project to .Net 4.5 to be able to use latest FsCheck. I also updated the fake script to use 4.5, but I'm getting a weird error when running the tests via Fake on this PR:

image

Running the tests inside FSI work fine, do you have any idea what could be the problem?

**Comment by forki** [comment]
Oupsis. Are there different fscheck.dlls? Will try to look into this. Maybe I find some time this evening.

**Comment by ovatsus** [comment]
No, just one FsCheck. BTW, running with TestDriven.Net inside VS also gives the same error...

**Comment by forki** [comment]
Mhm. Wondering @kurtschelfthout has seen this before.

**Comment by ovatsus** [comment]
This only seems to fail on Windows, on mono the tests pass

**Comment by forki** [comment]
My gut feeling is: this is another instancr

**Comment by ovatsus** [comment]
Humm, actually appVeyor is failing for some other reason, this test pass, so it seems it's only a problem on my machine. Maybe because I also have VS2015 installed, and the fake command line picks up F# 4.0 instead of F# 3.1?

**Comment by ovatsus** [comment]
It does work on FSI on both VS2013 and VS2015

**Comment by forki** [comment]
Yep that might be an issue

**Comment by ovatsus** [comment]
I'll try to uninstall F# 4.0 and VS2015 to see if it fixes the issue

**Comment by kurtschelfthout** [comment]
Definitely all the symptoms of some FSharp.Core compatibility issue. Try adding app.config redirects?

**Comment by ovatsus** [comment]
Ok, I think the problem is that FSharp.Data.Tests used 4.3.0.0, and FsCheck used 4.3.1.0

**Comment by ovatsus** [comment]
Problem solved, thanks

**Pull request merged**
