### PR TITLE
Revert "Update FAKE version"

### PR DESCRIPTION
**Pull request by ovatsus**
Reverts fsharp/FSharp.Data#1042

### CODE REVIEW

**Comment by ovatsus** [comment]
@forki had to revert this, as I get a ton of compiler errors after updating FAKE. It seems that the fact that FAKE is using dot net core is leaking inside the compilation, and FSharp.Data doesn't support dotnet core yet

**Comment by ovatsus** [comment]
It's weird that on appVeyor it works fine, though, but it doesn't on my machine :/

**Comment by ovatsus** [comment]
C:\Git\FSharp.Data\src\unknown(1,1): error FS0219: The referenced or default base CLI library 'mscorlib' is binary-incompatible with the referenced F# core library 'C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSha
           rp.Core.dll'. Consider recompiling the library or making an explicit reference to a version of this library that matches the CLI version you are using. [C:\Git\FSharp.Data\src\FSharp.Data.Portable47.fsproj]

**Comment by forki** [comment]
.net core? are you sure?

**Comment by ovatsus** [comment]
Or maybe it's just FSharp.Core 4.1 vs FSharp.Core 4.0

**Comment by forki** [comment]
probably

**Comment by ovatsus** [comment]
Though why would FAKE affect the compilation?

**Comment by matthid** [comment]
?

**Comment by forki** [comment]
I don't think FAKE.exe is the issue. It's probably "just" that it now detects newer MSBuild to build your projects. And MSBuild ist not completly backwards compatible.

what I saw was that couple of your projects to reference FSharp.Core from packages folder but from GAC. run paket install to fix that

**Comment by ovatsus** [comment]
`paket install` doesn't fix it. With FAKE 4.36, `build build` works fine, with FAKE 4.58.3, `build build` fails. I've swapped back and forward a couple of times and it's deterministic. And it's weird, as all projects reference FSharp.Core from GAC, but for a specific version

**Comment by ovatsus** [comment]
Actually, not from GAC, from the Refernece Assemblies folder

**Comment by forki** [comment]
Ok what's concrete error? Where does it happen? Is it MSBuild related. So
many questions. Yes fake version changed but what did that mean for the
build on your machine?

Am 11.04.2017 14:01 schrieb "Gustavo Guerra" <notifications@github.com>:

**Comment by ovatsus** [comment]
This is the error `The referenced or default base CLI library 'mscorlib' is binary-incompatible with the referenced F# core library 'C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Core.dll`

I did a diff of the FAKE output, and the problem seems to be that with the old FAKE, VS2015 is being used, with the new one, VS2017 is being used

Old FAKE:

    Building project: C:\Git\FSharp.Data\FSharp.Data.sln
      C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe  C:\Git\FSharp.Data\FSharp.Data.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Git\FSharp.Data\packages\FAKE\tools\FakeLib.dll"
    C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe  C:\Git\FSharp.Data\FSharp.Data.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Git\FSharp.Data\packages\FAKE\tools\FakeLib.dll"
    Microsoft (R) Build Engine version 14.0.25420.1
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 11/04/2017 13:06:09.
         1>Project "C:\Git\FSharp.Data\FSharp.Data.sln" on node 1 (Rebuild target(s)).
         1>ValidateSolutionConfiguration:
             Building solution configuration "Release|Any CPU".
         1>Project "C:\Git\FSharp.Data\FSharp.Data.sln" (1) is building "C:\Git\FSharp.Data\src\FSharp.Data.fsproj" (2) on node 1 (Rebuild target(s)).
         2>GenerateTargetFrameworkMonikerAttribute:
           Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
           CoreCompile:
             C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -o:obj\Release\FSharp.Data.dll --debug:pdbonly --noframework --define:TRACE --doc:bin\Release\FSharp.Data.xml --optimize+ -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.Linq.dll" --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --highentropyva- --warnon:1182 "C:\Users\guguer\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs" Net\UriUtils.fs Net\Http.fs CommonRuntime\IO.fs CommonRuntime\Caching.fs CommonRuntime\TextConversions.fs CommonRuntime\TextRuntime.fs CommonRuntime\Pluralizer.fs CommonRuntime\NameUtils.fs CommonRuntime\StructuralTypes.fs CommonRuntime\StructuralInference.fs Json\JsonValue.fs Json\JsonConversions.fs Json\JsonExtensions.fs Json\JsonRuntime.fs Xml\XmlRuntime.fs Csv\CsvRuntime.fs Csv\CsvFile.fs Csv\CsvExtensions.fs Csv\CsvInference.fs WorldBank\WorldBankRuntime.fs Html\HtmlCharRefs.fs Html\HtmlParser.fs Html\HtmlOperations.fs Html\HtmlCssSelectors.fs Html\HtmlInference.fs Html\HtmlRuntime.fs Runtime.fs AssemblyInfo.fs 

New FAKE:

    Building project: C:\Git\FSharp.Data\FSharp.Data.sln
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe  C:\Git\FSharp.Data\FSharp.Data.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Git\FSharp.Data\packages\FAKE\tools\FakeLib.dll"
    Microsoft (R) Build Engine version 15.1.1012.6693
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 11/04/2017 13:07:55.
         1>Project "C:\Git\FSharp.Data\FSharp.Data.sln" on node 1 (Rebuild target(s)).
         1>ValidateSolutionConfiguration:
             Building solution configuration "Release|Any CPU".
         1>Project "C:\Git\FSharp.Data\FSharp.Data.sln" (1) is building "C:\Git\FSharp.Data\src\FSharp.Data.fsproj" (2) on node 1 (Rebuild target(s)).
         2>GenerateTargetFrameworkMonikerAttribute:
           Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
           CoreCompile:
             C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsc.exe -o:obj\Release\FSharp.Data.dll
             --debug:pdbonly
             --noframework
             --define:TRACE
             --doc:bin\Release\FSharp.Data.xml
             --optimize+
             -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll
             -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll
             -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll
             -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll
             -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.dll
             -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.Linq.dll
             --target:library
             --warn:3
             --warnaserror:76
             --fullpaths
             --flaterrors
             --highentropyva-
             --warnon:1182
             C:\Users\guguer\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs
             Net\UriUtils.fs
             Net\Http.fs
             CommonRuntime\IO.fs
             CommonRuntime\Caching.fs
             CommonRuntime\TextConversions.fs
             CommonRuntime\TextRuntime.fs
             CommonRuntime\Pluralizer.fs
             CommonRuntime\NameUtils.fs
             CommonRuntime\StructuralTypes.fs
             CommonRuntime\StructuralInference.fs
             Json\JsonValue.fs
             Json\JsonConversions.fs
             Json\JsonExtensions.fs
             Json\JsonRuntime.fs
             Xml\XmlRuntime.fs
             Csv\CsvRuntime.fs
             Csv\CsvFile.fs
             Csv\CsvExtensions.fs
             Csv\CsvInference.fs
             WorldBank\WorldBankRuntime.fs
             Html\HtmlCharRefs.fs
             Html\HtmlParser.fs
             Html\HtmlOperations.fs
             Html\HtmlCssSelectors.fs
             Html\HtmlInference.fs
             Html\HtmlRuntime.fs
             Runtime.fs
             AssemblyInfo.fs
             

And VS2017 tried to reference `C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\FSharp.Core.dll` for the portable library project, which is wrong.

I need to figure out why VS2017/F#4.1 doesn't compile FSharp.Data properly, but why does updating FAKE causes a different version of VS to be used?

**Comment by forki** [comment]
It's not VS.
It's MSBuild.

The thing is as I wrote above. Fake now detects newer MSBuild versions
(which is important or we could not build new stuff). But Microsoft did not
make MSBuild fully backwards compatible.
So you either need to make fsharp.data work with modern MSBuild or tell
fake to use old MSBuild.

Am 11.04.2017 14:14 schrieb "Gustavo Guerra" <notifications@github.com>:

**Comment by ovatsus** [comment]
How can I tell FAKE to use MSBuild 2015 instead of MSBuild 2017?

**Comment by ovatsus** [comment]
Doing `set VisualStudioVersion=14.0` before running fake works, but is there a better way to do that by passing a parameter to the msbuild task instead? It seems it only takes the full msbuil exe path as a parameter

**Comment by forki** [comment]
you can set a environment variable at the beginning of the build script:

    - On all OS's, we check a `MSBuild` environment variable which is either
        * a direct path to a file to use, or
        * a directory that contains a file called `msbuild` on non-Windows systems, or `MSBuild.exe` on Windows systems

    - In addition, on Windows systems we
       * try to read the MSBuild tool location from the AppSettings file using a parameter named `MSBuild`, and finally
       * if a `VisualStudioVersion` environment variable is specified, we try to use the specific MSBuild version, matching that Visual Studio version.

**Comment by ovatsus** [comment]
Replaced with #1045

**Pull request closed without merging**
