### PR TITLE
Fix issue #1255 : EmbeddedResource not working

### PR DESCRIPTION
**Pull request by fpellet**
I take old version of FSharp.TypeProviders.SDK

Fix issue #1255

### CODE REVIEW

**Comment by dsyme** [comment]
Hi @fpellet, We need to get to the bottom of this issue rather than reverting to the old TPSDK.  

Do you happen to know the root change to the TPSDK that caused problem?

**Comment by fpellet** [comment]
Hi @dsyme 
I think it's the next version that I locked. After, I did not find the exact problem source. This isn't the easiest function to understand :)

**Comment by dsyme** [comment]
So perhaps this change: https://github.com/fsprojects/FSharp.TypeProviders.SDK/commit/dff4ef5d9e0f6130586326069bef25efc64c427f#diff-7c540ae6a67f14c48d0403e7b021fc86L7954

**Comment by fpellet** [comment]
The last version fix this bug  
I rebase and rollback commit 965c2d1  
Now, this PR add only a test to detect regression

**Comment by dsyme** [comment]
Thank you!!!

**Pull request merged**
