### PR TITLE
Fix Csv.Save() Data Corruption trap: If x.Save(file) is called and file already exists, delete it and then…

### PR DESCRIPTION
**Pull request by nhirschey**
This is to fix the unexpected behavior in this issue: https://github.com/fsharp/FSharp.Data/issues/1242

I can't think of a scenario where you would want to (partially) write over a pre-existing file that you are calling x.Save() on. I found this investigating why csv files I was creating were corrupted with bad data after I changed data and tried resaving the resulting csv. 

I also think this behavior is more consistent with csv saving features of other languages people using this library might be coming from (SAS, R, Stata, etc.).

### CODE REVIEW

**Comment by dsyme** [comment]
Close/open to re-run CI

**Comment by nightroman** [comment]
Would not it be better to open the file with the "override" option instead of deleting? Presumably, this way is more effective preserves file permissions, too.

**Comment by nhirschey** [comment]
I do not know what the "override if exists" code is. I just know that without this fix, file.Save("...") corrupts data if the new csv file has fewer rows than the original that it is replacing.

If there's a more common code conventionfor replacing a file if it exists, I'm fine with that.

**Comment by nightroman** [comment]
I think it's [FileStream(String, FileMode, FileAccess, FileShare)](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netframework-4.7.2#System_IO_FileStream__ctor_System_String_System_IO_FileMode_System_IO_FileAccess_System_IO_FileShare_) with `FileMode` set to `Create`.

**Comment by nightroman** [comment]
or this `File.Open(<path>, FileMode.Create, FileAccess.Write, FileShare.None)) ...`

**Comment by nightroman** [comment]
I think the simplest way is to replace the original line

    let writer = new StreamWriter(File.OpenWrite(path))

with

    let writer = new StreamWriter(path)

This constructor uses `append = false`, i.e. the existing file is overridden.
That is how Deedle writes CSV, see
https://github.com/fslaborg/Deedle/blob/f0d3a2e61268e9d666b1f95cd371e135aa74c071/src/Deedle/FrameExtensions.fs#L641

**Comment by nhirschey** [comment]
Thanks for the link to Deedle’s version. I’ll update to that, and the Deedle reference will help justify the pull request.

**Comment by nhirschey** [comment]
The new version follows the example of Deedle to ensure data corruption does not occur when a user calls CsvFile.Save(path) where path is an existing file on disk.

As an example of the new functionality is below. See the referenced issue for the behavior in the current released version. 

```fsharp
#r """packages\FSharp.Data\lib\net45\FSharp.Data.dll"""
open FSharp.Data
open System

type MyCsvType =
  CsvProvider<Schema = "A (int), B (string), C (date option)",
    HasHeaders=false>

let myRows =
  [ MyCsvType.Row(1, "a", None)
    MyCsvType.Row(2, "B", Some DateTime.Now) ]

let file = __SOURCE_DIRECTORY__ + "/test.csv"
let myCsv = new MyCsvType(myRows)
myCsv.Save(file)

IO.File.ReadAllLines(file)
// Here is the original file
//val it : string [] = [|"1,a,"; "2,B,2019-04-16T11:34:37.5933828+01:00"|]

type MyCsvType2 =
  CsvProvider<Schema = "A (string), B (string), C (date option)",
    HasHeaders=false>

let myRows =
  [ MyCsvType2.Row("blah", "a", None) ]

let myCsv2 = new MyCsvType2(Seq.take 1 myRows)
myCsv2.Save(file)

IO.File.ReadAllLines(file)

// This version correctly only has one line in the resulting file.
// val it : string [] = [|"blah,a,"|]
```

**Pull request merged**
