### PR TITLE
Replace CommonProviderImplementation with updated TP SDK (WIP)

### PR DESCRIPTION
**Pull request by ovatsus**

### CODE REVIEW

**Comment by ovatsus** [comment]
@dsyme I'm having this error when compiling the test project:

    parse error FS3033: error : Object reference not set to an instance of an object.

Can you have a look?

**Comment by ovatsus** [comment]
(it assumes this code: https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/83)

**Comment by ovatsus** [comment]
Ping
@dsyme, I'll need help here, have no idea why this is not working

**Comment by dsyme** [comment]
@ovatsus I only just saw this (notifications had been going to a subfolder) - did you get it sorted out in the end?  Thanks.

**Comment by ovatsus** [comment]
@tpetricek is continuing this here: https://github.com/fsharp/FSharp.Data/pull/931

**Comment by tpetricek** [comment]
@dsyme It all works now. I made a few PRs for the TP starter pack and merged them to get this sorted out.

**Comment by dsyme** [comment]
Thank you so much

**Pull request closed without merging**
