### PR TITLE
Use ApplyPolicy with ReflectionOnlyLoad based on name (improve #821)

### PR DESCRIPTION
**Pull request by tpetricek**
A better fix for the #821 issue, as suggested by @veikkoeeva. I tested this on my Azure VM and it worked fine.

### CODE REVIEW

**Comment by tpetricek** [comment]
BTW: What are the current release plans for F# Data? It would be nice to get new releases out reasonably frequently. Having this released for the [May 14 hands-on-session in London](http://www.meetup.com/FSharpLondon/events/222161266/) would be nice... :-) 

I'm not yet 100% sure if I'll need this (I was debugging this on Azure VM), but I don't expect the machines running Azure Web apps would have `FSharp.Core.dll` in the GAC....

**Comment by tpetricek** [comment]
(Also, please let me know if I actually broke the build, or if this is caused by some earlier changes..!)

**Comment by ovatsus** [comment]
That failure was just SourceLink, which always fails on PRs, this looks good

**Comment by ovatsus** [comment]
I'll do a release with this soon

**Comment by tpetricek** [comment]
Wonderful, thanks a lot!

**Comment by ovatsus** [comment]
Published

**Comment by tpetricek** [comment]
:+1:

**Pull request merged**
