### PR TITLE
Support parsing as DateTimeOffset when there is offset present in the date time string

### PR DESCRIPTION
**Pull request by zpbappi**
Initiated by #970 

However, as I needed to add a new primitive type `DateTimeOffset`, I had to modify codes for common runtime and XmlProvider in order to compile and make the tests pass. I would consider it adds DateTimeOffset parsing capability in general to the library.

Supports parsing `DateTimeOffset` as from the following format:
- iso 8601
- /Date(`millis`[+-]`4-digit offset`)/

_Note_: If there are date time entries both with and without an offset in a collection, the type is inferred as `DateTime`.

### CODE REVIEW

**Comment by zpbappi** [comment]
I have made this PR WIP. Once the issues with Http tests are resolved, possibly by #986 or some other way, I will remove the changes I made in tests from this PR and resubmit again.

**Comment by jschiefer** [comment]
I would like to see this one move forward, so that those of us not in Cambridge or London can also have their tests succeed. Anything I can do to help?

**Comment by zpbappi** [comment]
@dsyme, @tpetricek: do we have some sort of bot to mention who will trigger the CI build again?

**Comment by jschiefer** [comment]
You can always add an appropriate quote from Dr. Who to an arbitrary file on your branch.

**Comment by zpbappi** [comment]
Something wrong with TraviCI. It downloads mono successfully, but cannot run `mono` from build.sh. I will try to reproduce that in Docker and see if I can actually mimic TravicCI environment. 

However, please have a look at the changes as this PR changes the way DateTime is parsed. _It is bigger on the inside_  (@jschiefer, there you go...)

**Comment by colinbull** [comment]
Am I correct in thinking this will actually make DateTimeOffset the default datetime primitive now? If so then this is a breaking change, It would be nice (if this is the case), to have a way to revert to the old behavior.

**Comment by zpbappi** [comment]
@colinbull I am not sure whether DateTimeOffset becomes the default datetime primitive. However, it will try to parse any string in _DateTime+Offset_ format as DateTimeOffset first. Well, there is an exception to it. If you have a mixed collection of DateTime and DateTimeOffset types, the collection type will become DateTime collection. But, you are right about this PR having some breaking changes. e.g. the GitHub.json test in JsonProvider.fsx. The timestamps there were being parsed as DateTime objects, although the string contains _DateTime + offset_. So, it will break with the implementation of DateTimeOffset parsing, as the timestamps will be parsed as DateTimeOffset objects.

**Comment by jschiefer** [comment]
@zpbappi, have you been able to gain some new insights on the Travis issues? This is very odd...

**Comment by ovatsus** [comment]
#135

**Comment by ovatsus** [comment]
Hi @zpbappi, I was trying to push a merge with the current master to this PR branch but I don't have permissions. Would you mind turning this on? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by zpbappi** [comment]
@ovatsus done.

**Comment by zpbappi** [comment]
@ovatsus I only see two test failures now and they seem logical at the first glance. Will try to fix by this weekend.

**Comment by ovatsus** [comment]
Thanks

**Comment by ovatsus** [comment]
I'm looking into getting this into 3.0

**Comment by zpbappi** [comment]
Oh, my eyes! I haven't seen that much green in a while... I guess the problem is _EXTERMINATEd_. Feel free merge and close.

**Comment by ovatsus** [comment]
Thanks. Can you also update the docs before I merge this?

**Comment by zpbappi** [comment]
@ovatsus updated the documentation. I just realized, parsing of string into `DateTimeOffset` is only available for JSON. Don't we want it for CSV, HTML, and others?

**Comment by ovatsus** [comment]
Yes, it should apply to all of them, not just JSON

**Comment by zpbappi** [comment]
@ovatsus I will add the parsing to all other types. That is- CSV, HTML, Text (please add if anything is missing). You also mentioned something about including this in 3.0. How long do we have?

**Comment by ovatsus** [comment]
No deadline, no worries. I want to get the datetime and the timezone change s in because they're breaking changes, but I'll wait till they're ready

**Comment by ovatsus** [comment]
Sorry for the delay looking at this, thanks for updating this to support the other type providers.
If I understood correctly, almost every date will be inferred as DateTimeOffset with this change now, not only when an explicit offset is used. In which cases will DateTime still be used?

**Comment by zpbappi** [comment]
@ovatsus 

> almost every date will be inferred as DateTimeOffset with this change now

Not really. If the format is a _known_ DateTimeOffset format, it will be parsed as DateTimeOffset. Otherwise it will be treated as DateTime. Here are three tests explaining the scenarios:
1. [for CSV data](https://github.com/fsharp/FSharp.Data/pull/980/files#diff-a5c5684880691154645529d05f1d3780R101)
2. [for HTML data](https://github.com/fsharp/FSharp.Data/pull/980/files#diff-0f0e0a0216751577e96a912a170092e0R348)
3. [for JSON data](https://github.com/fsharp/FSharp.Data/pull/980/files#diff-c0101ec91479b9eab425418bd2fdeba2R679)

Finally, [this test](https://github.com/fsharp/FSharp.Data/pull/980/files#diff-d87904431698335b6eb9ab6394892a0bR45) demonstrates the _known_ DateTimeOffset formats.

**Comment by ovatsus** [comment]
Merged this. Will be released as part of 3.0.0-beta5

**Comment by ovatsus** [comment]
Sorry it took me more than 2 years to finally merge this :/

**Comment by zpbappi** [comment]
@ovatsus No worries. Happy to contribute something.

**Pull request merged**
