### PR TITLE
update TPSDK and paket targets

### PR DESCRIPTION
**Pull request by dsyme**
This updates the TPSDK to contain the fix for #1249 

thanks
don

### CODE REVIEW

**Comment by dsyme** [comment]
Error: 
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Fake.Core.BuildFailedException: Target 'Build' failed. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'C:\projects\fsharp-data\FSharp.Data.DesignTime'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
```

**Comment by dsyme** [comment]
OK, well, there seem to be problems building the repo.  On my local machine I get
```
       SourceLinkCreate:
         git rev-parse --show-toplevel
         'git' is not recognized as an internal or external command,
         operable program or batch file.
     1>C:\Users\dsyme\.nuget\packages\sourcelink.create.commandline\2.8.0\build\SourceLink.Create.CommandLine.targets(21,5): error MSB3073: The command "git rev-parse --show-toplevel" exited with code 9009. [C:\GitHub\dsyme\FSharp.Data\src\FSharp.Data.DesignTime\FSharp.Data.DesignTime.fsproj]
```

**Comment by baronfel** [comment]
Ugh, we need to update the version of sourcelink used to the non-clitool version to sidestep this class of errors: https://github.com/dotnet/sourcelink

**Comment by dsyme** [comment]
@baronfel It looks like the build with the MSBuild toolchain has been busted for a while, even before 3.0.0 release

I just added a commit to remove the use of the MSBuild toolchain altogether, to see how it goes, and see if we can get CI green

If we get it green we can consider bringing back the MSBuild toolchain - though as long as we're testing on .NET Core and .NET Framework it may be enough (obviously it would be good to test on Mono too, but  maybe the `dotnet` chain is doing that anyway)

**Comment by dsyme** [comment]
Hmmm 
* appveyor is green and a nuget has been produced.  
* On windows tests have been run on both `netcoreapp2.0` and `net461`

So that's a good sign.

**Comment by dsyme** [comment]
CI seems much healthier now

@ovatsus @baronfel If it's green in the morning I'll tag this as 3.0.1 and we can release a new nuget - this is quite an important fix for #1249

**Comment by dsyme** [comment]
ok, green it is. And Mono testing is included on travis:
```
Test run for /home/travis/build/fsharp/FSharp.Data/tests/FSharp.Data.DesignTime.Tests/bin/Release/netcoreapp2.0/FSharp.Data.DesignTime.Tests.dll(.NETCoreApp,Version=v2.0)

e/travis/build/fsharp/FSharp.Data/tests/FSharp.Data.DesignTime.Tests/bin/Release/net461/FSharp.Data.DesignTime.Tests.dll(.NETFramework,Version=v4.6.1)
```

Will pull this and tag

**Comment by ovatsus** [comment]
@dsyme do you want me to do the 3.01 release today? Or I can give you permission to the nuget package as well so you can do it

**Comment by ovatsus** [comment]
Released 3.01 and added you as owner of the nuget package

**Comment by dsyme** [comment]
> Released 3.01 and added you as owner of the nuget package

Thank you!  Great to have this released.

**Pull request merged**
