### PR TITLE
Update FAKE version

### PR DESCRIPTION
**Pull request by forki**
see https://github.com/fsharp/FAKE/issues/1515

### CODE REVIEW

**Comment by BlythMeister** [comment]
I think the targets at the bottom also need updating.
It could still try running tests before build on the  "All" target.

**Comment by ovatsus** [comment]
I think I prefer the old behaviour and will wait for the FAKE fix

**Comment by forki** [comment]
keeping this for testing

**Comment by forki** [comment]
looks like FAKE is back to normal

**Comment by ovatsus** [comment]
Great!

**Pull request merged**
