### PR TITLE
Parse time spans

### PR DESCRIPTION
**Pull request by johannesegger**
Replacement for #1023 and #1000

### CODE REVIEW

**Comment by ovatsus** [comment]
Looks good, sorry for not reviewing earlier
A couple of requests:
* Can you update TimeSpans.json to also have a field that almost looks like a timespan but actually doesn't parse as one?
* Can you also add tests for CSV and XML using timespans, similarly to what you've done for JSON?

**Comment by ovatsus** [comment]
Hi @johannesegger, I'm looking into getting this into 3.0, would you mind adding those extra tests and updating the documentation?

**Comment by johannesegger** [comment]
Sorry, I don't think I have time for that until July.

**Comment by baronfel** [comment]
@johannesegger if you'd like I can take this across the finish line by adding those tests?

**Comment by johannesegger** [comment]
Yes, absolutely, thanks a lot 👍

**Comment by baronfel** [comment]
@ovatsus the failure in travis was a temporal http request one, I don't think it's relevant.
The failure in appveyor is because we're trying to install the dotnet sdk and don't need to. I think this one is also not a blocker because the dotnet sdk build on the other OSs works fine.

**Comment by ovatsus** [comment]
@johannesegger, @baronfel , @zpbappi or anyone else, would you mind updating this PR adding signature tests and updating the documentation?

**Comment by ovatsus** [comment]
I've added the signature tests, only documentation missing

**Comment by zpbappi** [comment]
@ovatsus I missed the memo as I live in the down under. Anyway, do you still need any help with this?

**Comment by zpbappi** [comment]
@ovatsus I looked at the changes. However, I am attending MSOpenHack for 3 days and will not get a chance before Friday to work on this. Hope this is okay.

**Comment by ovatsus** [comment]
Of course it's ok :)

**Comment by zpbappi** [comment]
@ovatsus Just realized, I cannot update a source branch of the PR, as I am not a maintainer. Anyway, I have a separate PR targetting to the source branch to include the update. Here it is: https://github.com/johannesegger/FSharp.Data/pull/2
It turned out to be surprisingly simple- unless I missed something. A really great PR by @johannesegger. Sorry, it took so long. Could not manage time earlier.

**Comment by zpbappi** [comment]
I looked at the AppVeyor failed dotnetcore build. It looks like a permission issue for fake while deleting a directory. here's the relevant log secion: https://ci.appveyor.com/project/ovatsus/fsharp-data/build/3.0.0-beta5-a1810041921/job/t75bybwacwtmpvvc#L2673

**Comment by ovatsus** [comment]
Thank you both, it builds and passes tests ok locally, so merging it

**Pull request merged**
