### PR TITLE
Correct release dates in RELEASE_NOTES.md

### PR DESCRIPTION
**Pull request by kevmal**

### CODE REVIEW

**Comment by dsyme** [comment]
Hi @kevmal - would you like to become a 2nd maintainer on this repo, with the ability to accept pull requests and push releases?

Thanks
Don

**Comment by kevmal** [comment]
Sure, I can help out where needed.

**Comment by dsyme** [comment]
Hi @kevmal, that's great.  Can you send me your nuget ID?

**Comment by dsyme** [comment]
Hi @kevmal, I've added you to the maintainers - you now have permissions to accept PRs in this repo.  I will also give you permission to push nuget packages.

Welcome aboard!

**Comment by kevmal** [comment]
Thanks! nuget id is the same, kevmal

**Pull request merged**
