### PR TITLE
Type Provider for Statistical Data published by Bank for International Settlements 

### PR DESCRIPTION
**Pull request by dmicic**
Type provider for the [BIS statistics](http://www.bis.org/statistics/full_data_sets.htm). More information can be found here: [Post about BIS Type Provider](http://blog.micic.ch/net/bis-statistics-f-type-provider-alpha-version) (Although, the API has slightly changed since then)

I'm seeking some feedback on my first code written in a functional language :)
Unit tests will be written if structure is good enough and you are interested in merging the branch to master. 

Example:
`
open FSharp.Data.Runtime.Bis.Implementation
type prices = FSharp.Data.Bis&lt;"C:\full_WEBSTATS_LONG_PP_DATAFLOW_csv.csv"&gt;

[&lt;EntryPoint&gt;]
let main argv = 
    printfn "%A" argv

```
let context = new prices.QueryContext()
context.``Reference area`` <- [ prices.``Reference area``.``CH:Switzerland`` ]


let filter = context.Get()
let result = query filter context.DataSource

0
```

`

### CODE REVIEW

**Comment by tpetricek** [comment]
I wonder if it would make more sense to add this to the [F# Data Toolbox project](http://fsprojects.github.io/FSharp.Data.Toolbox/)?

It is an easier to use collection of additional data access components that are more specialized and might not make that much sense for everyone using the F# Data library. It also does not support that many target profiles, so it is easier to build and release more quickly.

(Also, it seems that your blog post is down :-(... )

**Comment by dmicic** [comment]
Thanks! I was thinking it would fit here since the WorldBank data provider is here as well.
I am in the process of moving my webhost. :( I will let you know as soon as the blog post is up and running again.

**Comment by dmicic** [comment]
@tpetricek The [blog post](http://blog.micic.ch/net/bis-statistics-f-type-provider-alpha-version) went down probably 2-3h before you open it. :) It should be up an running again. Please have a look and let me know what you think. From my point of view, is very similar to the WorldBank provider, except that the BIS does not provide and webservice yet.

**Comment by dsyme** [comment]
@dmicic Awesomme work! I agree that F# Data Toolbox would be a great place for this

**Comment by dsyme** [comment]
@tpetricek @ovatsus  AppVeyor looks red for FSharp.Data - what's needed to get it green? thanks

**Comment by ovatsus** [comment]
For some weird reason FsCheck started failing when running from the Fake command line, though inside the VS test runner still works fine

**Comment by Thorium** [comment]
I think this PR can be closed as it's merged to FSharp.Data.Toolbox

**Pull request closed without merging**
