### PR TITLE
[WiP] Use the updated type provider SDK

### PR DESCRIPTION
**Pull request by tpetricek**
Trying to finish the work that @ovatsus started to use the TP starter pack.

### CODE REVIEW

**Comment by tpetricek** [comment]
Almost there, I think I just need to tweak the output for strings :)

**Comment by dsyme** [comment]
For some reason I thought I had done this work, sorry!

**Comment by tpetricek** [comment]
Woohoo, all passing now :)

**Comment by ovatsus** [comment]
Yay!

**Pull request merged**
