### PR TITLE
Update JsonProvider.fsx

### PR DESCRIPTION
**Pull request by psfinaki**
I was struggling with that and things were not working until I found [this comment](https://github.com/fsharp/FSharp.Data/issues/1191#issuecomment-609921277) noting that point about project file. I think it would be useful for others as well.

### CODE REVIEW

**Comment by nhirschey** [comment]
1. In dotnet core, does "MyLib" also need to be added to the embedded embedded resource string? Such as in

```fsharp
type WB = JsonProvider<"../data/WorldBank.json", 
 EmbeddedResource="MyLib, MyLib.worldbank.json"
```

  I'm looking at https://github.com/fsharp/FSharp.Data/blob/08f351820f8b44c21ac6fb5afb30be0236332d0d/tests/FSharp.Data.Tests/JsonProvider.fs#L19

2. It would also be nice to show explicitly how to include the embedded resource in the project file.

**Comment by psfinaki** [comment]
@nhirschey,
1. Well my case was dotnet core, so yes
2. Added a link to MSDN, there is also a screenshot with options, I guess it should be sufficient

**Comment by nhirschey** [comment]
Yeah, my point is to make dotnet core the default, so change line 303 to

```fsharp
  EmbeddedResource="MyLib, MyLib.worldbank.json">
```

**Comment by nhirschey** [comment]
I also ran into this last week with FSharp.Data.Toolbox, and knowing that in dotnet core you need MyLib at the front would have helped. Just trying to help the next poor souls so they don't have our issues ;)

**Comment by psfinaki** [comment]
Oh that thing, yeah sure, added the path there :)

**Pull request merged**
